module.exports = {
    teams: 4,
    rounds: 2,
    players: [
        {name:"***REMOVED***", male:true, vector:4},
        {name:"***REMOVED***", male:true, vector:4},
        {name:"***REMOVED***", male:true, vector:4},
        {name:"***REMOVED***", male:true, vector:4},
        {name:"***REMOVED***", male:true, vector:4},
        {name:"***REMOVED***", male:true, vector:4},
        {name:"***REMOVED***", male:true, vector:4},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:false, vector:3},
        {name:"***REMOVED***", male:false, vector:3},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:false, vector:3},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:false, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:false, vector:2},
        {name:"***REMOVED***", male:false, vector:2},
        {name:"***REMOVED***", male:false, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:false, vector:1},
        {name:"***REMOVED***", male:true, vector:1},
        {name:"***REMOVED***", male:true, vector:1},
        {name:"***REMOVED***", male:true, vector:1},
        {name:"***REMOVED***", male:true, vector:1},
        {name:"***REMOVED***", male:true, vector:1},
        {name:"***REMOVED***", male:true, vector:1},
        {name:"***REMOVED***", male:false, vector:1},
        {name:"***REMOVED***", male:false, vector:1},
        {name:"***REMOVED***", male:true, vector:1},
    ]
}