module.exports = {
    checkinEvery: 1e5,
    teams: 4,
    rounds: 5,
    players: [
        {name:"***REMOVED***", male:true, vector:4, tall:true},
        {name:"***REMOVED***", male:true, vector:4, tall:true},
        {name:"***REMOVED***", male:true, vector:4},
        {name:"***REMOVED***", male:true, vector:4, tall:true},
        {name:"***REMOVED***", male:true, vector:4},
        {name:"***REMOVED***", male:true, vector:4},
        {name:"***REMOVED***", male:true, vector:4},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:false, vector:3},
        {name:"***REMOVED***", male:false, vector:3},
        {name:"***REMOVED***", male:true, vector:3, tall:true},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:false, vector:3},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:true, vector:3},
        {name:"***REMOVED***", male:false, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:true, vector:2, tall:true},
        {name:"***REMOVED***", male:false, vector:2},
        {name:"***REMOVED***", male:false, vector:2},
        {name:"***REMOVED***", male:false, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:true, vector:2, tall:true},
        {name:"***REMOVED***", male:true, vector:2},
        {name:"***REMOVED***", male:false, vector:1},
        {name:"***REMOVED***", male:true, vector:1},
        {name:"***REMOVED***", male:true, vector:1},
        {name:"***REMOVED***", male:true, vector:1},
        {name:"***REMOVED***", male:true, vector:1},
        {name:"***REMOVED***", male:true, vector:1, tall:true},
        {name:"***REMOVED***", male:true, vector:1},
        {name:"***REMOVED***", male:false, vector:1},
        {name:"***REMOVED***", male:false, vector:1},
        {name:"***REMOVED***", male:true, vector:1, tall:true},
    ]
}